--- !ruby/object:Jumpstart::Configuration
application_name: Agree.Live
business_name: Lawing S.R.L.
domain: staging.agree.live
support_email: no-reply@staging.agree.live
default_from_email: Agree.Live <no-reply@staging.agree.live>
business_address: ''
background_job_processor: async
email_provider: ''
personal_accounts: false
livereload: false
solargraph: false
register_with_account: true
payment_processors:
- stripe
