--- !ruby/object:Jumpstart::Configuration
application_name: Agree.Live
business_name: Lawing S.R.L.
domain: agreev2.herokuapp.com
support_email: no-reply@agreev2.herokuapp.com
default_from_email: Agree.Live <no-reply@agreev2.herokuapp.com>
business_address: ''
background_job_processor: async
email_provider: 'sendgrid'
personal_accounts: false
livereload: false
solargraph: false
register_with_account: true
payment_processors:
- stripe
